on: 
  pull_request:
  push:
    branches: 
      - '*'

jobs:
  compile:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: compile
        env:
          WORKSPACE: ${{ GITHUB_WORKSPACE }}
        uses: ./.github/workflows/actions/compile
