on: 
  pull_request:
  push:
    branches: 
      - '*'

jobs:
  compile:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: copy dockerfile
        # awful hack because COPY ../ doesn't work in Dockerfile
        run: cp ./dockerfiles/compile/Dockerfile ./Dockerfile
      - name: compile
        uses: ./.github/workflows/actions/compile
